apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.0.4/manifests/ha/install.yaml
- argocd-ns.yaml
- argocd-ingress.yaml
# - argocd-cm.yaml
# - argocd-secret.yaml
# - argocd-rbac-cm.yaml 
# - argocd-cmd-params-cm.yaml
# - argocd-repo-creds.yaml
# - argocd-repositories.yaml
# - argocd-ssh-known-hosts-cm.yaml
# - argocd-tls-certs-cm.yaml

