---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: argocd
spec:
  project: linkerd
  destination:
    server: https://kubernetes.default.svc
    namespace: linkerd
  source:
    chart: linkerd2
    repoURL: https://helm.linkerd.io/stable
    targetRevision: 2.11.0
  # helm:
  #   parameters:
  #   - name: identityTrustAnchorsPEM
  #     value: |
  #       -----BEGIN CERTIFICATE-----
  #       
  #       -----END CERTIFICATE-----          
