apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
bases:
- ./crds
- ./ingress
resources:
- traefik-ns.yaml
- traefik-rbac.yaml
- traefik-deployment.yaml
- traefik-svc.yaml