#
# See here for haproxy ingress controller values https://github.com/haproxy-ingress/charts/blob/release-0.13/haproxy-ingress/README.md#configuration
#
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy-ingress-operator
  namespace: haproxy-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy-ingress
      version: "0.13.9"
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
      interval: 1m
  values:
    controller:
      hostNetwork: true