#
# See here for haproxy ingress controller values https://github.com/haproxy-ingress/charts/blob/release-0.13/haproxy-ingress/README.md#configuration
#
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubernetes-haproxy-ingress
  namespace: kubernetes-ingress
spec:
  interval: 5m
  chart:
    spec:
      chart: kubernetes-ingress
      version: "1.16.3"
      sourceRef:
        kind: HelmRepository
        name: haproxytech
        namespace: flux-system
      interval: 1m
  values:
    controller:
      hostNetwork: true