---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: haproxytech
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://haproxytech.github.io/helm-charts