---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://haproxy-ingress.github.io/charts