---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: linkerd
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://helm.linkerd.io/stable